---
- name: System Setup
  hosts: Fedora
  tags: system
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
      tags: always
  roles:
    - role: user
      tags: user
    - role: zsh
      tags: zsh
    - role: vscode
      tags: vscode
    - role: ansible
      tags: ansible
    - role: common
      tags: common
    - role: system
      tags: system

- name: Development Environment
  hosts: Fedora
  tags: dev
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
      tags: always
  roles:
    - role: go
      tags: go
    - role: java
      tags: java
    - role: ruby
      tags: ruby
    - role: cpp
      tags: cpp
    - role: python
      tags: python
    - role: kubernetes
      tags: kubernetes
    - role: virtualization
      tags: virtualization
    - role: intellij
      tags: intellij
    - role: ai
      tags: ai
