---
- name: System Setup
  hosts: MacOS
  tags: system
  gather_facts: true
  roles:
    - role: user
      tags: user
    - role: homebrew
      tags: homebrew
    - role: zsh
      tags: zsh

- name: Development Environment
  hosts: MacOS
  tags: dev
  gather_facts: true
  roles:
    - role: java
      tags: java
    - role: go
      tags: go
    - role: python
      tags: python

- name: IDEs
  hosts: MacOS
  tags: ides
  gather_facts: true
  roles:
    - role: vscode
      tags: vscode

- name: Infrastructure
  hosts: MacOS
  tags: infra
  gather_facts: true
  roles:
    - role: kubernetes
      tags: kubernetes
