---
- name: System Setup
  hosts: MacOS
  tags: system
  roles:
    - role: user
      tags: user
    - role: homebrew
      tags: homebrew
    - role: zsh
      tags: zsh
    - role: vscode
      tags: vscode
