---
- name: User - create workspace folder
  become: true
  ansible.builtin.file:
    path: "{{ user_home_base_dir }}/{{ item.username }}/workspace"
    state: directory
    owner: "{{ item.username }}"
    group: staff
    mode: '0755'
  loop: "{{ users }}"

- name: User - create local bin folders
  become: true
  ansible.builtin.file:
    path: "{{ user_home_base_dir }}/{{ item[0].username }}/{{ item[1] }}"
    state: directory
    owner: "{{ item[0].username }}"
    group: staff
    mode: '0755'
  loop: "{{ users | product(['bin', '.local/bin']) | list }}"
