---
- name: User - include Linux specific tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: User - include macOS specific tasks
  ansible.builtin.include_tasks: macos.yml
  when: ansible_facts['os_family'] == 'Darwin'
