---
- name: Cpp - Load Linux tasks
  ansible.builtin.include_tasks: cpp-linux.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Cpp - Load macOS tasks
  ansible.builtin.include_tasks: cpp-macos.yml
  when: ansible_facts['os_family'] == 'Darwin'
