# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty32"

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

  config.vm.provision "shell" do |s|
  s.inline = <<-SHELL
    sudo apt-get update
    sudo apt-get install -y git 
    git clone https://github.com/ottenwbe/developer-environment-setup.git
    cd developer-environment-setup    
    chmod 774 bootstrap_local.sh
    ./bootstrap_local.sh hosts Ubuntu
  SHELL
  end

  #config.vm.provision "ansible" do |ansible|
  #  ansible.verbose = "v"
  #  ansible.playbook = "../../playbook.yml"bootstrap_local.sh
  #end
  
end
	
