---
- name: Kubernetes - Load Linux tasks
  ansible.builtin.include_tasks: k8s-linux.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Kubernetes - Load macOS tasks
  ansible.builtin.include_tasks: k8s-macos.yml
  when: ansible_facts['os_family'] == "Darwin"
