---
- name: go - download go 
  get_url:
    url: "https://dl.google.com/go/go{{ go_version }}.tar.gz"
    dest: ~/go.tar.gz
    mode: '0540'
- name: go - install go
  become: true
  shell: cd ~/ && tar -xzf ~/go.tar.gz && mv go /opt/
- name: go - cleanup install
  become: true
  file: 
    path: ~/go.tar.gz
    state: absent
- name: go - Generate startup script
  become: true
  template:
    mode: '0555'
    src: go-startup.j2  
    dest: "/etc/profile.d/go-startup.sh"


- name: go - get version
  become: true
  shell: go version
  register: goversion
- debug: msg="{{ goversion.stdout }}"

