---
- name: Ansible - Load Linux tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Ansible - Load macOS tasks
  ansible.builtin.include_tasks: macos.yml
  when: ansible_facts['os_family'] == "Darwin"
