---
# Packages for Fedora (RedHat family)
kubernetes_fedora_packages:
  - kubernetes-client
  - helm

# Packages for macOS (Darwin family)
kubernetes_macos_packages:
  - kubernetes-cli
  - helm
  - minikube
  - argocd
