- name: tools - general
  become: true
  package: name={{ item }} state=latest
  with_items:
    - curl
    - keepassxc
- name: tools - productivity
  become: true
  package: name={{ item }} state=latest
  with_items:
    - git
    - vagrant    
- name: tools - productivity
  become: true
  package: name={{ item }} state=latest
  with_items:
    - vim
    - nano
    - evince
    - libreoffice    
