ARG FEDORA_VERSION=43 # renovate: datasource=docker depName=fedora
FROM fedora:${FEDORA_VERSION}
# Install Ansible
RUN dnf -y update \
    && dnf install -y python3 python3-pip \
    && pip3 install ansible 